version: x.x.{build}
image: Visual Studio 2019
configuration: Release
install:
- cmd: git submodule update --init --recursive
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: dnSpy/dnSpy/bin/Release/net472
  name: dnSpy-net472
- path: dnSpy/dnSpy/bin/Release/netcoreapp3.0/win-x86/publish
  name: dnSpy-netcore-win32
- path: dnSpy/dnSpy/bin/Release/netcoreapp3.0/win-x64/publish
  name: dnSpy-netcore-win64
